/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_HX8379C_WVGA_VIDEO_H_
#define _PANEL_HX8379C_WVGA_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config hx8379c_wvga_video_panel_data = {
	"qcom,mdss_dsi_hx8379c_wvga_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution hx8379c_wvga_video_panel_res = {
	480, 854, 100, 94, 40, 0, 6, 4, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info hx8379c_wvga_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/

static char hx8379c_wvga_nop[] = {
	0x00,0x00,0x0,0x00
};

static char hx8379c_wvga_reset[] = {
	0x01,0x00,0x05,0x80
};

static char hx8379c_wvga_exit_inversion[] = {
	0x20,0x00,0x05,0x80
};

static char hx8379c_wvga_enter_inversion[] = {
	0x21,0x00,0x05,0x80
};

static char hx8379c_wvga_all_black[] = {
	0x22,0x00,0x05,0x80
};

static char hx8379c_wvga_all_white[] = {
	0x23,0x00,0x05,0x80
};

static char hx8379c_wvga_ext_set[] = {
	0x04,0x00,0x39,0xC0,
	0xB9,0xFF,0x83,0x79
};

static char hx8379c_wvga_set_power[] = {
	0x15,0x00,0x39,0xC0,
	0xB1,0x44,0x18,0x18,
	0x31,0x51,0x90,0xD0,
	0xEE,0xD4,0x80,0x38,
	0x38,0xF8,0x44,0x44,
	0x42,0x00,0x80,0x30,
	0x00
};

static char hx8379c_wvga_set_display[] = {
	0x0A,0x00,0x39,0xC0,
	0xB2,0x80,0xFE,0x0A,
	0x03,0x30,0x50,0x11,
	0x42,0x1D
};

static char hx8379c_wvga_set_cycle_timing[] = {
	0x0E,0x00,0x39,0xC0,
	0xB4,0x01,0x28,0x00,
	0x34,0x00,0x34,0x17,
	0x3A,0x17,0x3A,0xB0,
	0x00,0xFF
};

static char hx8379c_wvga_set_panel[] = {
	0xCC,0x02,0x15,0x80
};

static char hx8379c_wvga_unknown_cmd1[] = {
	0xD2,0x33,0x15,0x80
};

static char hx8379c_wvga_set_gip_timing[] = {
	0x1E,0x00,0x39,0xC0,
	0xD3,0x00,0x07,0x00,
	0x00,0x00,0x06,0x06,
	0x32,0x10,0x03,0x00,
	0x03,0x03,0x5F,0x03,
	0x5F,0x00,0x08,0x00,
	0x08,0x35,0x33,0x07,
	0x07,0x37,0x07,0x07,
	0x37,0x07
};

static char hx8379c_wvga_forward_gip_sequence[] = {
	0x21,0x00,0x39,0xC0,
	0xD5,0x18,0x18,0x19,
	0x19,0x18,0x18,0x20,
	0x21,0x24,0x25,0x18,
	0x18,0x18,0x18,0x00,
	0x01,0x04,0x05,0x02,
	0x03,0x06,0x07,0x18,
	0x18,0x18,0x18,0x18,
	0x18,0x18,0x18,0x18,
	0x18
};

static char hx8379c_wvga_backward_gip_sequence[] = {
	0x21,0x00,0x39,0xC0,
	0xD6,0x18,0x18,0x18,
	0x18,0x19,0x19,0x25,
	0x24,0x21,0x20,0x18,
	0x18,0x18,0x18,0x05,
	0x04,0x01,0x00,0x03,
	0x02,0x07,0x06,0x18,
	0x18,0x18,0x18,0x18,
	0x18,0x18,0x18,0x18,
	0x18
};

static char hx8379c_wvga_gamma_curve[] = {
	0x2B,0x00,0x39,0xC0,
	0xE0,0x00,0x05,0x09,
	0x26,0x26,0x3E,0x1E,
	0x45,0x08,0x0C,0x0D,
	0x17,0x0E,0x12,0x15,
	0x13,0x14,0x12,0x1F,
	0x1F,0x1F,0x00,0x05,
	0x09,0x26,0x26,0x3E,
	0x1E,0x45,0x08,0x0C,
	0x0D,0x17,0x0E,0x12,
	0x15,0x13,0x14,0x12,
	0x1F,0x1F,0x1F
};

static char hx8379c_wvga_vcom_voltage[] = {
	0x03,0x00,0x39,0xC0,
	0xB6,0x54,0x54,0xFF
};

static char hx8379c_wvga_tear_off[] = {
	0x34,0x00,0x05,0x80
};

static char hx8379c_wvga_tear_on[] = {
	0x35,0x00,0x15,0x80
};

static char hx8379c_wvga_brightness[] = {
	0x51,0xff,0x15,0x80
};

static char hx8379c_wvga_ctrl_display[] = {
	0x53,0x2c,0x15,0x80
};

static char hx8379c_wvga_adaptive_brightness[] = {
	0x55,0x01,0x15,0x80
};

static char hx8379c_wvga_enter_sleep[] = {
	0x10, 0x00, 0x05, 0x80
};

static char hx8379c_wvga_exit_sleep[] = {
	0x11, 0x00, 0x05, 0x80
};

static char hx8379c_wvga_display_off[] = {
	0x28, 0x00, 0x05, 0x80
};

static char hx8379c_wvga_display_on[] = {
	0x29, 0x00, 0x05, 0x80
};




static struct mipi_dsi_cmd hx8379c_wvga_video_on_command[] = {
	{sizeof(hx8379c_wvga_ext_set),               hx8379c_wvga_ext_set,               0},
	{sizeof(hx8379c_wvga_set_power),             hx8379c_wvga_set_power,             0},
	{sizeof(hx8379c_wvga_set_display),           hx8379c_wvga_set_display,           0},
	{sizeof(hx8379c_wvga_set_cycle_timing),      hx8379c_wvga_set_cycle_timing,      0},
	{sizeof(hx8379c_wvga_set_panel),             hx8379c_wvga_set_panel,             0},
	{sizeof(hx8379c_wvga_unknown_cmd1),          hx8379c_wvga_unknown_cmd1,          0},
	{sizeof(hx8379c_wvga_set_gip_timing),        hx8379c_wvga_set_gip_timing,        0},
	{sizeof(hx8379c_wvga_forward_gip_sequence),  hx8379c_wvga_forward_gip_sequence,  0},
	{sizeof(hx8379c_wvga_backward_gip_sequence), hx8379c_wvga_backward_gip_sequence, 0},
	{sizeof(hx8379c_wvga_gamma_curve),           hx8379c_wvga_gamma_curve,           0},
	{sizeof(hx8379c_wvga_vcom_voltage),          hx8379c_wvga_vcom_voltage,          0},
	{sizeof(hx8379c_wvga_tear_off),              hx8379c_wvga_tear_off,              0},
	{sizeof(hx8379c_wvga_brightness),            hx8379c_wvga_brightness,            0},
	{sizeof(hx8379c_wvga_ctrl_display),          hx8379c_wvga_ctrl_display,          0},
	{sizeof(hx8379c_wvga_adaptive_brightness),   hx8379c_wvga_adaptive_brightness,   0},
	{sizeof(hx8379c_wvga_exit_sleep),            hx8379c_wvga_exit_sleep,          150},
	{sizeof(hx8379c_wvga_display_on),            hx8379c_wvga_display_on,           20},	
};

#define HX8379C_WVGA_VIDEO_ON_COMMAND 17



static struct mipi_dsi_cmd hx8379c_wvga_video_off_command[] = {
	{0x4, hx8379c_wvga_display_off, 50},
	{0x4, hx8379c_wvga_enter_sleep, 120}
};

#define HX8379C_WVGA_VIDEO_OFF_COMMAND 2


static struct command_state hx8379c_wvga_video_state = {
	0, 0
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info hx8379c_wvga_video_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info hx8379c_wvga_video_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration hx8379c_wvga_video_lane_config = {
	2, 0, 1, 1, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t hx8379c_wvga_video_timings[] = {
	0x8b, 0x1f, 0x14, 0x00, 0x45, 0x4a, 0x19, 0x23, 0x23, 0x03, 0x04, 0x00

};


static struct panel_timing hx8379c_wvga_video_timing_info = {
	0, 4, 0x04, 0x1b
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence hx8379c_wvga_video_reset_seq = {
	{ 1, 0, 1, }, { 20, 200, 20, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight hx8379c_wvga_video_backlight = {
	1, 1, 4095, 100, 1, "PMIC_8941"
};

#endif /*_PANEL_HX8379C_WVGA_VIDEO_H_*/
